version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: d9_loan_project_new
    container_name: loan-application
    restart: unless-stopped        
    networks:
      - loan

  httpd:
    build:
      context: ./
      dockerfile: Dockerfile.httpd
    image: loan-application-httpd
    container_name: loan-application-httpd
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - loan
networks:
  loan:
     driver: bridge
