"""First revision

Revision ID: 5e403fb4bf5b
Revises: edce59e6faaf
Create Date: 2022-12-03 15:51:43.453845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e403fb4bf5b'
down_revision = 'edce59e6faaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NDT.new_mortgage', 'muser')
    op.drop_column('NDT.new_mortgage', 'mclient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NDT.new_mortgage', sa.Column('mclient', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('NDT.new_mortgage', sa.Column('muser', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
