"""First revision

Revision ID: edce59e6faaf
Revises: 
Create Date: 2022-12-03 15:45:04.812499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edce59e6faaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NDT.new_mortgage', sa.Column('muser', sa.String(), nullable=True))
    op.add_column('NDT.new_mortgage', sa.Column('mclient', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NDT.new_mortgage', 'mclient')
    op.drop_column('NDT.new_mortgage', 'muser')
    # ### end Alembic commands ###
